src/ComptageMaker/ComptageBundle/Entity/TextBlock.php
<?php

namespace ComptageMaker\ComptageBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * TextBlock
 */
class TextBlock
{
    /**
     * @var integer
     */
    private $id;

    /**
     * @var string
     */
    private $text;

    /**
     * @var string
     */
    private $title;

    /**
     * @var integer
     */
    private $blockOrder;

    /**
     * Get id
     *
     * @return integer 
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * Set text
     *
     * @param string $text
     * @return TextBlock
     */
    public function setText($text)
    {
        $this->text = $text;
    
        return $this;
    }

    /**
     * Get text
     *
     * @return string 
     */
    public function getText()
    {
        return $this->text;
    }

    /**
     * Set title
     *
     * @param string $title
     * @return TextBlock
     */
    public function setTitle($title)
    {
        $this->title = $title;
    
        return $this;
    }

    /**
     * Get title
     *
     * @return string 
     */
    public function getTitle()
    {
        return $this->title;
    }

    /**
     * Set blockOrder
     *
     * @param integer $blockOrder
     * @return TextBlock
     */
    public function setOrder($blockOrder)
    {
        $this->blockOrder = $blockOrder;
    
        return $this;
    }

    /**
     * Get blockOrder
     *
     * @return integer 
     */
    public function getOrder()
    {
        return $this->blockOrder;
    }
}

src/ComptageMaker/ComptageBundle/Form/PlageType.php
<?php

namespace ComptageMaker\ComptageBundle\Form;

use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class PlageType extends AbstractType
{
        /**
     * @param FormBuilderInterface $builder
     * @param array $options
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('nom','text', array(
                'required' => true,
                'label' => 'Nom de la plage',
            ))
            ->add('debut','time', array(
                'input' => 'datetime',
                'widget' => 'choice',
                'required' => true,
                'label' => 'Début de la plage',
            ))
            ->add('fin','time',array(
                'input' => 'datetime',
                'widget' => 'choice',
                'required' => true,
                'label' => 'Fin de la plage',
            ))
        ;
    }
    
    /**
     * @param OptionsResolverInterface $resolver
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        $resolver->setDefaults(array(
            'data_class' => 'ComptageMaker\ComptageBundle\Entity\Plage'
        ));
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'comptagemaker_comptagebundle_plage';
    }
}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/association.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Créer Association{% endblock %}

{% block div %}

{% endblock %}

{% block body %}
    <form method="post" {{ form_enctype(form) }} class="well">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>{{ form_label(form.name) }}</th>
                    <td>{{ form_widget(form.name) }}</td>
                    <td>{{ form_errors(form.name) }}</td>
                </tr>
                <tr>
                    <td>{{ form_rest(form) }}</td>
                    <td><input type="submit" class="btn btn-primary" /></td>
                </tr>
            </table>
        </div>
    </form>

{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/comptage.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Créer Comptage{% endblock %}

{% block div %}

{% endblock %}

{% block body %}
    <form method="post" {{ form_enctype(form) }} class="well">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>{{ form_label(form.date) }}</th>
                    <td>{{ form_widget(form.date) }}</td>
                    <td>{{ form_errors(form.date) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.briefing) }}</th>
                    <td>{{ form_widget(form.briefing) }}</td>
                    <td>{{ form_errors(form.briefing) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.etat) }}</th>
                    <td>{{ form_widget(form.etat) }}</td>
                    <td>{{ form_errors(form.etat) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.comment) }}</th>
                    <td>{{ form_widget(form.comment) }}</td>
                    <td>{{ form_errors(form.comment) }}</td>
                </tr>
                <tr>
                    <td>{{ form_rest(form) }}</td>
                    <td><input type="submit" class="btn btn-primary" /></td>
                </tr>
            </table>
        </div>
    </form>

{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/confirm.html.twig
Bonjour,<br/>

Nous vous confirmons par la présente votre inscription à la session {{ session.plage.nom }} du comptage du {{ include(
'ComptageMakerComptageBundle:Comptage:day.html.twig', { 'date': session.comptage.date })}}
<br/>

Nous vous rappelons que le briefing se fera le {{ include(
'ComptageMakerComptageBundle:Comptage:date.html.twig', { 'date' : session.comptage.briefing })}}
<br/>
En cas de problème, ou si vous souhaitez obtenir de plus amples informations, merci de nous recontacter à l'adresse comptages@24heures.org
<br/>
Salutations,
<br/>
L'équipe Comptages,<br/>
24 Heures de l'INSA

src/ComptageMaker/ComptageBundle/Resources/views/Admin/dashboard.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Dashboard{% endblock %}

{% block div %}

{% endblock %}

{% block body %}

    <h2>Dashboard d'Administration</h2>

    <div class="panel">
        <div class="panel-heading">
            Entité Plage
        </div>
        <div class="panel-body">
            <h3>Description</h3>
            <p></p>
        </div>
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Début</th>
                    <th>Fin</th>
                    <th><em>Edition</em></th>
                    <th><em>Suppression</em></th>
                </tr>
                {% for plage in plages %}
                    <tr>
                        <td>{{ plage.id }}</td>
                        <td>{{ plage.nom }}</td>
                        <td>{{ include('ComptageMakerComptageBundle:Comptage:daytime.html.twig', { 'date':plage.debut })}}</td>
                        <td>{{ include('ComptageMakerComptageBundle:Comptage:daytime.html.twig', { 'date':plage.fin })}}</td>
                        <td><a href="{{ path('plage_edit',{ 'id' : plage.id}) }}"><i class="glyphicon glyphicon-edit"></i></a></td>
                        <td><a href="{{ path('plage_remove', { 'id' : plage.id}) }}" onclick="return(confirm('Etes-vous sur?'));"><i class="glyphicon glyphicon-remove"></i></a></td>
                    </tr>
                {% endfor %}
                <tr>
                    <td><a href="{{ path('plage_create') }}"><i class="glyphicon glyphicon-plus"></i></a></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="panel">
        <div class="panel-heading">
            Entité Comptage
        </div>
        <div class="panel-body">
            <h3>Description</h3>
            <p></p>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Nombre de sessions</th>
                        <th>Date</th>
                        <th>Horaire du briefing</th>
                        <th>Etat</th>
                        <th>Commentaires</th>
                        <th><em>Edition</em></th>
                        <th><em>Suppression</em></th>
                    </tr>
                </thead>
                <tbody>
                {% for comptage in comptages %}
                    <tr>
                        <td>{{ comptage.id }}</td>
                        <td>{{ comptage.sessions | length }}</td>
                        <td>{{ include('ComptageMakerComptageBundle:Comptage:day.html.twig', { 'date':comptage.date }) }}</td>
                        <td>{{ include('ComptageMakerComptageBundle:Comptage:date.html.twig', { 'date':comptage.briefing }) }}</td>
                        <td>{% if comptage.etat %} Ouvert {% else %} Fermé {% endif %}</td>
                        <td>{{ comptage.comment }}</td>
                        <td><a href="{{ path('comptage_edit',{'id' : comptage.id}) }}"><i class="glyphicon glyphicon-edit"></i></a></td>
                        <td><a href="{{ path('comptage_remove', {'id' : comptage.id}) }}" onclick="return(confirm('Etes-vous sur?'));" ><i class="glyphicon glyphicon-remove"></i></a></td>
                    </tr>

                    <tr class="success">
                        <th>Session</th>
                        <th>Type</th>
                        <th>Places</th>
                        <th>Prix</th>
                        <th>Inscrits</th>
                        <th><em>Edition</em></th>
                        <th><em>Suppression</em></th>
                        <th>Mail</th>
                    </tr>
                    {% for session in comptage.sessions %}
                        <tr class="success">
                            <td>Session {{ session.plage.nom }}, id {{ session.id }}</td>
                            <td>Type : {{ session.type }}</td>
                            <td>Places : {{ session.entries }}</td>
                            <td>Prix : {{ session.prix }}€/h</td>
                            <td>Inscrits : {{ session.inscrits | length }}{% if session.inscrits != [] %}<a href="{{ path('session_showListInscrits',{'id' : session.id }) }}"><i class="glyphicon glyphicon-arrow-right"></i></a>{% endif %}</td>
                            <td><a href="{{ path('session_edit',{'id' : session.id}) }}"><i class="glyphicon glyphicon-edit"></i></a></td>
                            <td><a href="{{ path('session_remove', {'id' : session.id}) }}" onclick="return(confirm('Etes-vous sur?'));"><i class="glyphicon glyphicon-remove"></i></a></td>
                            <td><a href="{{ path('admin_mail_session', {'id' : session.id }) }}" onclick="return(confirm('Etes-vous sur?'));"><i class="glyphicon glyphicon-envelope"></i></a></td>
                        </tr>
                    {% endfor %}
                        <tr class="success">
                            <td><a href="{{ path('session_create', { 'comptageId': comptage.id }) }}"><i class="glyphicon glyphicon-plus"></i></a></td>
                        </tr>
                {% endfor %}
                <tr>
                    <td><a href="{{ path('comptage_create') }}"><i class="glyphicon glyphicon-plus"></i></a></td>
                </tr>
                </tbody>
            </table>
        </div>
    </div>

    <div class="panel">
        <div class="panel-heading">
            Entité TextBlock
        </div>
        <div class="panel-body">
            <h3>Description</h3>
            <p></p>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Titre</th>
                    <th>Texte</th>
                    <th>Ordre</th>
                    <th><em>Edition</em></th>
                    <th><em>Suppression</em></th>
                </tr>
                </thead>
                {% for textblock in textblocks %}
                <tbody>
                    <tr>
                        <td>{{ textblock.id }}</td>
                        <td>{{ textblock.title}}</td>
                        <td>{{ textblock.text | raw | nl2br }}</td>
                        <td>{{ textblock.order }}</td>
                        <td><a href="{{ path('textblock_edit', { 'id': textblock.id }) }}"><i class="glyphicon glyphicon-edit"></i></a></td>
                        <td><a href="{{ path('textblock_remove', { 'id': textblock.id}) }}" onclick="return(confirm('Etes-vous sur?'));"><i class="glyphicon glyphicon-remove"></i></a></td>
                    </tr>
                </tbody>
                {% endfor %}
                <tr>
                    <td><a href="{{ path('textblock_create') }}"><i class="glyphicon glyphicon-plus"></i></a></td>
                </tr>
            </table>
        </div>
    </div>

    <div class="panel">
        <div class="panel-heading">
            Entité Association
        </div>
        <div class="panel-body">
            <h3>Description</h3>
            <p></p>
        </div>
        <div class="table-responsive">
            <table class="table">
                <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th><em>Suppression</em></th>
                </tr>
                </thead>
                {% for association in associations %}
                <tbody>
                    <tr>
                        <td>{{ association.id }}</td>
                        <td>{{ association.name }}</td>
                        <td><a href="{{ path('association_remove', { 'id': association.id}) }}" onclick="return(confirm('Etes-vous sur?'));"><i class="glyphicon glyphicon-remove"></i></a></td>
                    </tr>
                </tbody>
                {% endfor %}
                <tr>
                    <td><a href="{{ path('association_create') }}"><i class="glyphicon glyphicon-plus"></i></a></td>
                </tr>
            </table>
        </div>
    </div>

{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/guide.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Admin guide{% endblock %}

{% block div %}

{% endblock %}

{% block body %}
    <h2>Guide d'utilisation de l'admin</h2>

    <h3>Etapes de création d'un comptage depuis le dashboard</h3>
    <ul>
        <li>Créer des plages horaires</li>
        <li>Créer un comptage</li>
        <li>Créer des sessions pour ce comptage</li>
        <li>S'assurer que des associations existent (recommandé)</li>
    </ul>

    <h3>Gestion de la page d'accueil depuis le dashboard</h3>
    <ul>
        <li>Créer une entité textblock</li>
        <li>Celles-ci sont affichées sur la page d'accueil dans l'ordre de leur création (ordre dans une màj future possible)</li>
        <li>S'inspirer de celles déjà existantes</li>
    </ul>
{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/listInscrits.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Inscription{% endblock %}

{% block div %}

{% endblock %}

{% block body %}
    <div class="table-responsive">
        <table class="table">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Nom</th>
                    <th>Prénom</th>
                    <th>Mail</th>
                    <th>Téléphone</th>
                    <th>Association</th>
                    <th>Voiture</th>
                    <th>Commentaires</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
            {% for inscrit in inscrits %}
                <tr>
                    <td>{{ inscrit.id }}</td>
                    <td>{{ inscrit.nom }}</td>
                    <td>{{ inscrit.prenom }}</td>
                    <td><a href="mailto:{{ inscrit.mail }}">{{ inscrit.mail }}</a></td>
                    <td>{{ inscrit.tel }}</td>
                    <td>{{ inscrit.association.name }}</td>
                    <td>{% if inscrit.voiture == true %}Oui{% else %}Non{% endif %}</td>
                    <td>{{ inscrit.commentaires }}</td>
                    <td><a href="{{ path('inscrit_remove', {'sessionId': sessionId, 'id' : inscrit.id}) }}" onclick="return(confirm('Etes-vous sur?'));"><i class="glyphicon glyphicon-remove-circle"></i></a></td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>

{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/login.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Connexion{% endblock %}

{% block div %}
    <br/>
    <h1>Connexion</h1>
{% endblock %}

{% block body %}
    {% if error is defined %}
        <div>{{ error }}</div>
    {% endif %}

<form class="form-horizontal" role="form" action="{{ path('comptage_login_check') }}" method="post">
        <fieldset>
        <legend>Connectez-vous</legend>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="username">Identifiant</label>
            <div class="col-sm-10">
                <input type="text" class="form-control input-lg" id="username" name="_username" value="{{ last_username }}" placeholder="Identifiant" />
            </div>
        </div>
        <div class="form-group">
            <label class="col-sm-2 control-label" for="password">Mot de passe</label>
            <div class="col-sm-10">
                <input type="password" class="form-control input-lg" id="password" name="_password" placeholder="Mot de Passe" />
            </div>
        </div>
        <div class="form-group">
            <div class="col-sm-offset-2 col-sm-10">
                <input type="submit" value="Connexion" class="btn btn-primary">
            </div>
        </div>
    </fieldset>
</form>
{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/newUser.html.twig
Bonjour Comptages,<br/>

<h3>Comptage: {{ include(
    'ComptageMakerComptageBundle:Comptage:day.html.twig', { 'date': count.date })}}</h3>
<h3>Inscrit(Prénom,Nom): {{ inscrit.prenom }} {{inscrit.nom }}</h3>
<h3>Association: {{ inscrit.association.name }}</h3>
<h3>Tél: {{ inscrit.tel }}</h3>
<h3>Mail: {{ inscrit.mail }}</h3>
<h3><a href="{{ url('admin_dashboard') }}">Lien du dashboard</a></h3>
{% for session in sessions %}
<h3>Session : {{ session.plage.nom }}</h3>
<h3>Nombre d'inscrits: {{ session.inscrits | length }}</h3>
<h3>Nombre de places prévues: {{ session.entries }}</h3>
<br/>
{% endfor %}
Nous lui avons rappelé que le briefing se fera le {{ include(
'ComptageMakerComptageBundle:Comptage:date.html.twig', { 'date' : count.briefing })}}
<br/>
En cas de problème, ou s'il souhaite obtenir de plus amples informations, il vous recontactera.
<br/>
<br/>
Salutations,<br/>
Le site des comptages,<br/>
24 Heures de l'INSA

src/ComptageMaker/ComptageBundle/Resources/views/Admin/newUserCount.html.twig
Bonjour Comptages,<br/>

<h3>Toutes les sessions du Comptage: {{ include(
    'ComptageMakerComptageBundle:Comptage:day.html.twig', { 'date': count.date })}}</h3>
<h3>Inscrit(Prénom,Nom): {{ inscrit.prenom }} {{inscrit.nom }}</h3>
<h3>Association: {{ inscrit.association.name }}</h3>
<h3>Tél: {{ inscrit.tel }}</h3>
<h3>Mail: {{ inscrit.mail }}</h3>
<h3><a href="http://comptagemaker.24heures.org{{ path('admin_dashboard') }}">Lien du dashboard</a></h3>
<h3>Nombre d'inscrits : </h3>
<ul>
    {% for session in count.sessions %}
    <li>session {{ session.id }}, {{ session.inscrits | length }} inscrits, {{ session.entries }} places prévues</li>
    {% endfor %}
</ul>
<br/>
Nous lui avons rappelé que le briefing se fera le {{ include(
'ComptageMakerComptageBundle:Comptage:date.html.twig', { 'date' : count.briefing })}}
<br/>
En cas de problème, ou s'il souhaite obtenir de plus amples informations, il vous recontactera.
<br/>
<br/>
Salutations,<br/>
Le site des comptages,<br/>
24 Heures de l'INSA

src/ComptageMaker/ComptageBundle/Resources/views/Admin/plage.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Créer Plage{% endblock %}

{% block div %}

{% endblock %}

{% block body %}
    <form method="post" {{ form_enctype(form) }} class="well">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>{{ form_label(form.nom) }}</th>
                    <td>{{ form_widget(form.nom) }}</td>
                    <td>{{ form_errors(form.nom) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.debut) }}</th>
                    <td>{{ form_widget(form.debut) }}</td>
                    <td>{{ form_errors(form.debut) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.fin) }}</th>
                    <td>{{ form_widget(form.fin) }}</td>
                    <td>{{ form_errors(form.fin) }}</td>
                </tr>
                <tr>
                    <td>{{ form_rest(form) }}</td>
                    <td><input type="submit" class="btn btn-primary" /></td>
                </tr>
            </table>
        </div>
    </form>

{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/session.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Créer Session{% endblock %}

{% block div %}

{% endblock %}

{% block body %}
    <form method="post" {{ form_enctype(form) }} class="well">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>{{ form_label(form.entries) }}</th>
                    <td>{{ form_widget(form.entries) }}</td>
                    <td>{{ form_errors(form.entries) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.type) }}</th>
                    <td>{{ form_widget(form.type) }}</td>
                    <td>{{ form_errors(form.type) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.prix) }}</th>
                    <td>{{ form_widget(form.prix) }}</td>
                    <td>{{ form_errors(form.prix) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.plage) }}</th>
                    <td>{{ form_widget(form.plage) }}</td>
                    <td>{{ form_errors(form.plage) }}</td>
                </tr>
                <tr>
                    <td>{{ form_rest(form) }}</td>
                    <td><input type="submit" class="btn btn-primary" /></td>
                </tr>
            </table>
        </div>
    </form>

{% endblock %}

src/ComptageMaker/ComptageBundle/Resources/views/Admin/textblock.html.twig
{% extends 'ComptageMakerComptageBundle::layout.html.twig' %}

{% block title %}ComptageMaker - Créer Textblock{% endblock %}

{% block div %}

{% endblock %}

{% block body %}
    <form method="post" {{ form_enctype(form) }} class="well">
        <div class="table-responsive">
            <table class="table">
                <tr>
                    <th>{{ form_label(form.title) }}</th>
                    <td>{{ form_widget(form.title) }}</td>
                    <td>{{ form_errors(form.title) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.text) }}</th>
                    <td>{{ form_widget(form.text) }}</td>
                    <td>{{ form_errors(form.text) }}</td>
                </tr>
                <tr>
                    <th>{{ form_label(form.order) }}</th>
                    <td>{{ form_widget(form.order) }}</td>
                    <td>{{ form_errors(form.order) }}</td>
                </tr>
                <tr>
                    <td>{{ form_rest(form) }}</td>
                    <td><input type="submit" class="btn btn-primary" /></td>
                </tr>
            </table>
        </div>
    </form>

{% endblock %}